[2024-01-09T10:39:09.878-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-10-17T10:00:00+00:00 [queued]>
[2024-01-09T10:39:09.882-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-10-17T10:00:00+00:00 [queued]>
[2024-01-09T10:39:09.882-0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-09T10:39:09.894-0300] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): extract_pokemons> on 2023-10-17 10:00:00+00:00
[2024-01-09T10:39:09.895-0300] {standard_task_runner.py:60} INFO - Started process 3906 to run task
[2024-01-09T10:39:09.897-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pokemon_extraction', 'extract_pokemons', 'scheduled__2023-10-17T10:00:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_extraction.py', '--cfg-path', '/tmp/tmp4r3a53sg']
[2024-01-09T10:39:09.898-0300] {standard_task_runner.py:88} INFO - Job 225: Subtask extract_pokemons
[2024-01-09T10:39:09.922-0300] {task_command.py:423} INFO - Running <TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-10-17T10:00:00+00:00 [running]> on host LAPTOP-SB6KEOGH.
[2024-01-09T10:39:09.968-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brenda Schapievski' AIRFLOW_CTX_DAG_ID='pokemon_extraction' AIRFLOW_CTX_TASK_ID='extract_pokemons' AIRFLOW_CTX_EXECUTION_DATE='2023-10-17T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-17T10:00:00+00:00'
[2024-01-09T10:39:10.278-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/brendaschap/airflow/dags/pokemon.py", line 22, in extract_pokemon
    pokemon_list.append(infos)
NameError: name 'infos' is not defined
[2024-01-09T10:39:10.281-0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=pokemon_extraction, task_id=extract_pokemons, execution_date=20231017T100000, start_date=20240109T133909, end_date=20240109T133910
[2024-01-09T10:39:10.296-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 225 for task extract_pokemons (name 'infos' is not defined; 3906)
[2024-01-09T10:39:10.310-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-09T10:39:10.320-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
