[2024-01-09T10:32:25.228-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-06-18T10:00:00+00:00 [queued]>
[2024-01-09T10:32:25.231-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-06-18T10:00:00+00:00 [queued]>
[2024-01-09T10:32:25.231-0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-09T10:32:25.243-0300] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): extract_pokemons> on 2023-06-18 10:00:00+00:00
[2024-01-09T10:32:25.245-0300] {standard_task_runner.py:60} INFO - Started process 3367 to run task
[2024-01-09T10:32:25.246-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pokemon_extraction', 'extract_pokemons', 'scheduled__2023-06-18T10:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_extraction.py', '--cfg-path', '/tmp/tmppwrtwv7a']
[2024-01-09T10:32:25.247-0300] {standard_task_runner.py:88} INFO - Job 104: Subtask extract_pokemons
[2024-01-09T10:32:25.268-0300] {task_command.py:423} INFO - Running <TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-06-18T10:00:00+00:00 [running]> on host LAPTOP-SB6KEOGH.
[2024-01-09T10:32:25.311-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brenda Schapievski' AIRFLOW_CTX_DAG_ID='pokemon_extraction' AIRFLOW_CTX_TASK_ID='extract_pokemons' AIRFLOW_CTX_EXECUTION_DATE='2023-06-18T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-18T10:00:00+00:00'
[2024-01-09T10:32:25.663-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/brendaschap/airflow/dags/pokemon.py", line 22, in extract_pokemon
    pokemon_list.append(infos)
NameError: name 'infos' is not defined
[2024-01-09T10:32:25.665-0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=pokemon_extraction, task_id=extract_pokemons, execution_date=20230618T100000, start_date=20240109T133225, end_date=20240109T133225
[2024-01-09T10:32:25.679-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 104 for task extract_pokemons (name 'infos' is not defined; 3367)
[2024-01-09T10:32:25.700-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-09T10:32:25.709-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
