[2024-01-09T10:30:41.306-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-05-18T10:00:00+00:00 [queued]>
[2024-01-09T10:30:41.309-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-05-18T10:00:00+00:00 [queued]>
[2024-01-09T10:30:41.309-0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-09T10:30:41.321-0300] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): extract_pokemons> on 2023-05-18 10:00:00+00:00
[2024-01-09T10:30:41.323-0300] {standard_task_runner.py:60} INFO - Started process 3302 to run task
[2024-01-09T10:30:41.324-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pokemon_extraction', 'extract_pokemons', 'scheduled__2023-05-18T10:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_extraction.py', '--cfg-path', '/tmp/tmpy7gswpu3']
[2024-01-09T10:30:41.325-0300] {standard_task_runner.py:88} INFO - Job 73: Subtask extract_pokemons
[2024-01-09T10:30:41.346-0300] {task_command.py:423} INFO - Running <TaskInstance: pokemon_extraction.extract_pokemons scheduled__2023-05-18T10:00:00+00:00 [running]> on host LAPTOP-SB6KEOGH.
[2024-01-09T10:30:41.387-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brenda Schapievski' AIRFLOW_CTX_DAG_ID='pokemon_extraction' AIRFLOW_CTX_TASK_ID='extract_pokemons' AIRFLOW_CTX_EXECUTION_DATE='2023-05-18T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-18T10:00:00+00:00'
[2024-01-09T10:30:41.707-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/brendaschap/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/brendaschap/airflow/dags/pokemon.py", line 22, in extract_pokemon
    pokemon_list.append(infos)
NameError: name 'infos' is not defined
[2024-01-09T10:30:41.709-0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=pokemon_extraction, task_id=extract_pokemons, execution_date=20230518T100000, start_date=20240109T133041, end_date=20240109T133041
[2024-01-09T10:30:41.726-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 73 for task extract_pokemons (name 'infos' is not defined; 3302)
[2024-01-09T10:30:41.740-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-09T10:30:41.750-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
